### ISSUE TITLE
Can't find it on NuGet.or

### ISSUE THREAD

**Issue by tlhintoq** [shrutinambiar/xamarin-forms-tinted-image#4]
Is this package active still?
No matter how I search through NuGet Package Manager in Visual Studio its not found.
Can't find it through NuGet.org

Makes me wonder about it.

**Comment by tlhintoq** [comment]
Update: I see now it is a class:Renderer arrangement.
Would be nice if this could be a versioned NuGet package so as to be informed of updates through an established mechanism.

This could also help with the depencies of things like:
`using CompositionProToolkit;` and `using Microsoft.Graphics`  in UWP which are not found and stopping that platform from building.

**Comment by RuddyOne** [comment]
Is this really not on NuGet? Its such a powerful little plugin it should be. Please get this sorted, I could see this being very popular!

**Comment by shrutinambiar** [comment]
@tlhintoq, @Ruddy2007  Really sorry for the delay. I finally found some time to restructure the control to a Plugin architecture. It's available on nuget here - https://www.nuget.org/packages/Plugin.CrossPlatformTintedImage/. Do refer to the README for setup details.
