### ISSUE TITLE
Invisible without tintcolor

### ISSUE THREAD

**Issue by Piees** [shrutinambiar/xamarin-forms-tinted-image#5]
Firstly thanks for the tinter! Works great except for when I don't want them initially tinted they become transparent/invisible. Could implementing default to image color or some warning in case tintcolor isnt specified?

**Comment by shrutinambiar** [comment]
Thanks for bringing this to my notice.

Setting to Transparent color was making the image invisible. I've updated the control to show the original image instead and disable tinting when this color is set.

Hope this resolves your issue :)
